FROM python:3.9-slim-buster

# set working directory
WORKDIR /usr/src/app

# system dependencies for sqlserver
RUN apt-get update \
  && apt-get -y install gcc \
  && apt-get -y install g++ \
  && apt-get -y install unixodbc unixodbc-dev \
  && apt-get clean

# system dependencies for postgres
RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2

# copy project file
COPY requirements.txt .

# install dependencies
RUN pip install -r requirements.txt

# copy all project
COPY . .

# run test
CMD sleep 60 && python ./test.py
